import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const stats = [
    { value: '35%', description: "of Amazon's revenue generated by its AI recommendation engine." },
    { value: '450%', description: "increase in ad click-throughs for JP Morgan Chase using AI copywriting." },
    { value: '90%', description: "reduction in herbicide use in agriculture via AI-powered 'See & Spray' tech." },
]

export default function HeroSection() {
    return (
        <section id="hero" className="py-20 lg:py-28 bg-card">
            <div className="container mx-auto px-4 text-center">
                <h1 className="text-4xl md:text-6xl font-bold tracking-tight font-headline text-foreground">
                    The AI Revolution in Action
                </h1>
                <p className="mt-6 max-w-3xl mx-auto text-lg md:text-xl text-muted-foreground">
                    An interactive exploration of how Artificial Intelligence is creating tangible value across industries. Discover the roles, tools, and strategies driving real-world impact.
                </p>
                <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
                    {stats.map((stat, index) => (
                        <Card key={index} className="text-center border-primary/20 shadow-lg hover:shadow-xl hover:shadow-primary/30 transition-shadow duration-300 bg-background">
                            <CardHeader>
                                <CardTitle className="text-5xl font-bold text-primary font-headline">
                                    {stat.value}
                                </CardTitle>
                            </CardHeader>
                            <CardContent>
                                <p className="text-muted-foreground">{stat.description}</p>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </div>
        </section>
    );
}
